image: ghcr.io/cirruslabs/flutter:3.24.5

stages:
  - test
  - secret-detection
  - validate

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .pub-cache/
    - .dart_tool/

variables:
  SECRET_DETECTION_ENABLED: 'true'
  PUB_CACHE: "$CI_PROJECT_DIR/.pub-cache"

before_script:
  - flutter --version
  - flutter pub get

secret_detection:
  stage: secret-detection

analyze:
  stage: validate
  script:
    - flutter analyze
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
